name = "summer-fog-9436"
main = "index.js"
compatibility_date = "2025-08-22"

[[durable_objects.bindings]]
name = "CHAT_SERVER"
class_name = "ChatServerV2"

# Gunakan tag yang lebih tinggi dari yang sudah ada
[[migrations]]
tag = "v6"
new_sqlite_classes = ["ChatServerV2"]
