name = "summer-fog-9436"
main = "index.js"
compatibility_date = "2025-08-22"

[[durable_objects.bindings]]
name = "CHAT_SERVER"
class_name = "ChatServer"

[[migrations]]
tag = "v3"
new_sqlite_classes = ["ChatServer"]
