name = "chat-cloudflare"
main = "index.js"
type = "module"
compatibility_date = "2025-08-22"

[durable_objects]
bindings = [
  { name = "CHAT_SERVER", class_name = "ChatServer" }
]

[[migrations]]
tag = "v1"
new_classes = ["ChatServer"]
