async fetch(request) {
  if (request.headers.get("Upgrade") === "websocket") {
    const [client, server] = Object.values(new WebSocketPair());
    server.accept();
    this.handleSocket(server);
    return new Response(null, { status: 101, webSocket: client });
  }
  return new Response("Expected websocket", { status: 400 });
}
